title: Class 11 Guide
description: A guide for building a Class 11 VW dune buggy.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
